# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Research
    url: "research"
    weight: 20
  - name: Notes
    url: "notes"
    weight: 30
  #- name: Events
  #  url: "events"
  #  weight: 40
  #- name: Work in Progress
  #  parent: research
  #  url: research/work_in_progress
  #  weight: 10
  #- name: Working Papers
  #  parent: research
  #  url: research/working_papers
  #  weight: 20
  #- name: Publications
  #  parent: research
  #  url: research/publications
  #  weight: 30      

  #- name: Posts
  #  url: '#posts'
  #  weight: 20
  #- name: Projects
  #  url: '#projects'
  #  weight: 30
  #- name: Talks
  #  url: '#talks'
  #  weight: 40
  #- name: Publications
  #  url: '#featured'
  #  weight: 50
  #- name: Contact
  #  url: '#contact'
  #  weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
